export const stockData = [
    {
        "id": 25903024,
        "token_id": "0",
        "num_sales": 0,
        "background_color": null,
        "image_url": "https://lh3.googleusercontent.com/9B1oTFEv4DeaW9gFwnd1ION2NzfGnC9lHfjnPNSbNkDZmID0P7Di6Y6ptZxZuf0oaWgnAKLu1eqEbdlCJSpHDFUceo2D7H9c0wK56Q",
        "image_preview_url": "https://lh3.googleusercontent.com/9B1oTFEv4DeaW9gFwnd1ION2NzfGnC9lHfjnPNSbNkDZmID0P7Di6Y6ptZxZuf0oaWgnAKLu1eqEbdlCJSpHDFUceo2D7H9c0wK56Q=s250",
        "image_thumbnail_url": "https://lh3.googleusercontent.com/9B1oTFEv4DeaW9gFwnd1ION2NzfGnC9lHfjnPNSbNkDZmID0P7Di6Y6ptZxZuf0oaWgnAKLu1eqEbdlCJSpHDFUceo2D7H9c0wK56Q=s128",
        "image_original_url": require("./assets/nfts/5.jpg"),
        "animation_url": null,
        "animation_original_url": null,
        "name": "Bandana Punk",
        "description": null,
        "external_link": null,
        "asset_contract": {
            "address": "0xb6f41e1cb14df0f8e84e86090eaf6802354e8d02",
            "asset_contract_type": "non-fungible",
            "created_date": "2022-01-02T06:21:35.483307",
            "name": "Bandana Punk",
            "nft_version": "3.0",
            "opensea_version": null,
            "owner": 4950061,
            "schema_name": "ERC721",
            "symbol": "CPP",
            "total_supply": "0",
            "description": "",
            "external_link": null,
            "image_url": "https://lh3.googleusercontent.com/9B1oTFEv4DeaW9gFwnd1ION2NzfGnC9lHfjnPNSbNkDZmID0P7Di6Y6ptZxZuf0oaWgnAKLu1eqEbdlCJSpHDFUceo2D7H9c0wK56Q=s120",
            "default_to_fiat": false,
            "dev_buyer_fee_basis_points": 0,
            "dev_seller_fee_basis_points": 0,
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": 0,
            "opensea_seller_fee_basis_points": 250,
            "buyer_fee_basis_points": 0,
            "seller_fee_basis_points": 250,
            "payout_address": "0x2d9bb967505eb2c5ee2b501fa02c823bacdd303a"
        },
        "permalink": "https://testnets.opensea.io/assets/0xb6f41e1cb14df0f8e84e86090eaf6802354e8d02/0",
        "collection": {
            "banner_image_url": null,
            "chat_url": null,
            "created_date": "2022-01-02T06:32:35.565855",
            "default_to_fiat": false,
            "description": "",
            "dev_buyer_fee_basis_points": "0",
            "dev_seller_fee_basis_points": "0",
            "discord_url": null,
            "display_data": {
                "card_display_style": "contain",
                "images": []
            },
            "external_url": null,
            "featured": false,
            "featured_image_url": null,
            "hidden": false,
            "safelist_request_status": "not_requested",
            "image_url": "https://lh3.googleusercontent.com/9B1oTFEv4DeaW9gFwnd1ION2NzfGnC9lHfjnPNSbNkDZmID0P7Di6Y6ptZxZuf0oaWgnAKLu1eqEbdlCJSpHDFUceo2D7H9c0wK56Q=s120",
            "is_subject_to_whitelist": false,
            "large_image_url": "https://lh3.googleusercontent.com/9B1oTFEv4DeaW9gFwnd1ION2NzfGnC9lHfjnPNSbNkDZmID0P7Di6Y6ptZxZuf0oaWgnAKLu1eqEbdlCJSpHDFUceo2D7H9c0wK56Q",
            "medium_username": null,
            "name": "Bandana Punk V4",
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": "0",
            "opensea_seller_fee_basis_points": "250",
            "payout_address": "0x2d9bb967505eb2c5ee2b501fa02c823bacdd303a",
            "require_email": false,
            "short_description": null,
            "slug": "bandana-punk-v4",
            "telegram_url": null,
            "twitter_username": null,
            "instagram_username": null,
            "wiki_url": null
        },
        "decimals": 0,
        "token_metadata": "https://ipfs.io/ipfs/bafkreid7l55dxr54ikiqjjjh44kd4qhexm5yvd4j2kmaqcfquequu2ef3e",
        "owner": {
            "user": {
                "username": null
            },
            "profile_img_url": require("./assets/owner/Screenshot.png"),
            "address": "0xff8f15c77db92f5388c0cf216e7fa6b51b49599b",
            "config": ""
        },
        "sell_orders": null,
        "creator": {
            "user": {
                "username": null
            },
            "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/32.png",
            "address": "0xff8f15c77db92f5388c0cf216e7fa6b51b49599b",
            "config": ""
        },
        "traits": [
            {
                "trait_type": "price",
                "value": "8",
                "display_type": null,
                "max_value": null,
                "trait_count": 1,
                "order": null
            }
        ],
        "last_sale": null,
        "top_bid": null,
        "listing_date": null,
        "is_presale": false,
        "transfer_fee_payment_token": null,
        "transfer_fee": null
    },
    {
        "id": 25903149,
        "token_id": "1",
        "num_sales": 0,
        "background_color": null,
        "image_url": "https://lh3.googleusercontent.com/hJKQWDj6ZUlEnBsdxH-_gK7sAosVTJjBLP_UE4TD-wVBFATfXgRJheHy1CGwp8Ly3Gz3yNvW7H9fJOjbyYt6qsmDzcld6ObliXouJz8",
        "image_preview_url": "https://lh3.googleusercontent.com/hJKQWDj6ZUlEnBsdxH-_gK7sAosVTJjBLP_UE4TD-wVBFATfXgRJheHy1CGwp8Ly3Gz3yNvW7H9fJOjbyYt6qsmDzcld6ObliXouJz8=s250",
        "image_thumbnail_url": "https://lh3.googleusercontent.com/hJKQWDj6ZUlEnBsdxH-_gK7sAosVTJjBLP_UE4TD-wVBFATfXgRJheHy1CGwp8Ly3Gz3yNvW7H9fJOjbyYt6qsmDzcld6ObliXouJz8=s128",
        "image_original_url":  require("./assets/nfts/4.jpg"),
        "animation_url": null,
        "animation_original_url": null,
        "name": "Cyber  Punk",
        "description": null,
        "external_link": null,
        "asset_contract": {
            "address": "0xb6f41e1cb14df0f8e84e86090eaf6802354e8d02",
            "asset_contract_type": "non-fungible",
            "created_date": "2022-01-02T06:21:35.483307",
            "name": "Bandana Punk",
            "nft_version": "3.0",
            "opensea_version": null,
            "owner": 4950061,
            "schema_name": "ERC721",
            "symbol": "CPP",
            "total_supply": "0",
            "description": "",
            "external_link": null,
            "image_url": "https://lh3.googleusercontent.com/9B1oTFEv4DeaW9gFwnd1ION2NzfGnC9lHfjnPNSbNkDZmID0P7Di6Y6ptZxZuf0oaWgnAKLu1eqEbdlCJSpHDFUceo2D7H9c0wK56Q=s120",
            "default_to_fiat": false,
            "dev_buyer_fee_basis_points": 0,
            "dev_seller_fee_basis_points": 0,
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": 0,
            "opensea_seller_fee_basis_points": 250,
            "buyer_fee_basis_points": 0,
            "seller_fee_basis_points": 250,
            "payout_address": "0x2d9bb967505eb2c5ee2b501fa02c823bacdd303a"
        },
        "permalink": "https://testnets.opensea.io/assets/0xb6f41e1cb14df0f8e84e86090eaf6802354e8d02/1",
        "collection": {
            "banner_image_url": null,
            "chat_url": null,
            "created_date": "2022-01-02T06:32:35.565855",
            "default_to_fiat": false,
            "description": "",
            "dev_buyer_fee_basis_points": "0",
            "dev_seller_fee_basis_points": "0",
            "discord_url": null,
            "display_data": {
                "card_display_style": "contain",
                "images": []
            },
            "external_url": null,
            "featured": false,
            "featured_image_url": null,
            "hidden": false,
            "safelist_request_status": "not_requested",
            "image_url": "https://lh3.googleusercontent.com/9B1oTFEv4DeaW9gFwnd1ION2NzfGnC9lHfjnPNSbNkDZmID0P7Di6Y6ptZxZuf0oaWgnAKLu1eqEbdlCJSpHDFUceo2D7H9c0wK56Q=s120",
            "is_subject_to_whitelist": false,
            "large_image_url": "https://lh3.googleusercontent.com/9B1oTFEv4DeaW9gFwnd1ION2NzfGnC9lHfjnPNSbNkDZmID0P7Di6Y6ptZxZuf0oaWgnAKLu1eqEbdlCJSpHDFUceo2D7H9c0wK56Q",
            "medium_username": null,
            "name": "Bandana Punk V4",
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": "0",
            "opensea_seller_fee_basis_points": "250",
            "payout_address": "0x2d9bb967505eb2c5ee2b501fa02c823bacdd303a",
            "require_email": false,
            "short_description": null,
            "slug": "bandana-punk-v4",
            "telegram_url": null,
            "twitter_username": null,
            "instagram_username": null,
            "wiki_url": null
        },
        "decimals": 0,
        "token_metadata": "https://ipfs.io/ipfs/bafkreiei7fmvcirehpwt7o7y443n5ithpkoohe23raimiiy7z3t5a3jrf4",
        "owner": {
            "user": {
                "username": null
            },
            "profile_img_url": require("./assets/owner/Screenshot.png"),
            "address": "0xff8f15c77db92f5388c0cf216e7fa6b51b49599b",
            "config": ""
        },
        "sell_orders": null,
        "creator": {
            "user": {
                "username": null
            },
            "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/32.png",
            "address": "0xff8f15c77db92f5388c0cf216e7fa6b51b49599b",
            "config": ""
        },
        "traits": [
            {
                "trait_type": "price",
                "value": "13",
                "display_type": null,
                "max_value": null,
                "trait_count": 1,
                "order": null
            }
        ],
        "last_sale": null,
        "top_bid": null,
        "listing_date": null,
        "is_presale": false,
        "transfer_fee_payment_token": null,
        "transfer_fee": null
    },
    {
        "id": 25903189,
        "token_id": "2",
        "num_sales": 0,
        "background_color": null,
        "image_url": "https://lh3.googleusercontent.com/WrmpbMJMKmGfjJRCu2b0Bp_Pk2iPZcuRXyqPj7p3-I19DKHlIluigjdiwsnUZA28ssIQcydOnYgD2f6Qra05gFMZHWuojV1JSbM",
        "image_preview_url": "https://lh3.googleusercontent.com/WrmpbMJMKmGfjJRCu2b0Bp_Pk2iPZcuRXyqPj7p3-I19DKHlIluigjdiwsnUZA28ssIQcydOnYgD2f6Qra05gFMZHWuojV1JSbM=s250",
        "image_thumbnail_url": "https://lh3.googleusercontent.com/WrmpbMJMKmGfjJRCu2b0Bp_Pk2iPZcuRXyqPj7p3-I19DKHlIluigjdiwsnUZA28ssIQcydOnYgD2f6Qra05gFMZHWuojV1JSbM=s128",
        "image_original_url": require("./assets/nfts/3.jpg"),
        "animation_url": null,
        "animation_original_url": null,
        "name": "Cigar hat Punk",
        "description": null,
        "external_link": null,
        "asset_contract": {
            "address": "0xb6f41e1cb14df0f8e84e86090eaf6802354e8d02",
            "asset_contract_type": "non-fungible",
            "created_date": "2022-01-02T06:21:35.483307",
            "name": "Bandana Punk",
            "nft_version": "3.0",
            "opensea_version": null,
            "owner": 4950061,
            "schema_name": "ERC721",
            "symbol": "CPP",
            "total_supply": "0",
            "description": "",
            "external_link": null,
            "image_url": "https://lh3.googleusercontent.com/9B1oTFEv4DeaW9gFwnd1ION2NzfGnC9lHfjnPNSbNkDZmID0P7Di6Y6ptZxZuf0oaWgnAKLu1eqEbdlCJSpHDFUceo2D7H9c0wK56Q=s120",
            "default_to_fiat": false,
            "dev_buyer_fee_basis_points": 0,
            "dev_seller_fee_basis_points": 0,
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": 0,
            "opensea_seller_fee_basis_points": 250,
            "buyer_fee_basis_points": 0,
            "seller_fee_basis_points": 250,
            "payout_address": "0x2d9bb967505eb2c5ee2b501fa02c823bacdd303a"
        },
        "permalink": "https://testnets.opensea.io/assets/0xb6f41e1cb14df0f8e84e86090eaf6802354e8d02/2",
        "collection": {
            "banner_image_url": null,
            "chat_url": null,
            "created_date": "2022-01-02T06:32:35.565855",
            "default_to_fiat": false,
            "description": "",
            "dev_buyer_fee_basis_points": "0",
            "dev_seller_fee_basis_points": "0",
            "discord_url": null,
            "display_data": {
                "card_display_style": "contain",
                "images": []
            },
            "external_url": null,
            "featured": false,
            "featured_image_url": null,
            "hidden": false,
            "safelist_request_status": "not_requested",
            "image_url": "https://lh3.googleusercontent.com/9B1oTFEv4DeaW9gFwnd1ION2NzfGnC9lHfjnPNSbNkDZmID0P7Di6Y6ptZxZuf0oaWgnAKLu1eqEbdlCJSpHDFUceo2D7H9c0wK56Q=s120",
            "is_subject_to_whitelist": false,
            "large_image_url": "https://lh3.googleusercontent.com/9B1oTFEv4DeaW9gFwnd1ION2NzfGnC9lHfjnPNSbNkDZmID0P7Di6Y6ptZxZuf0oaWgnAKLu1eqEbdlCJSpHDFUceo2D7H9c0wK56Q",
            "medium_username": null,
            "name": "Bandana Punk V4",
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": "0",
            "opensea_seller_fee_basis_points": "250",
            "payout_address": "0x2d9bb967505eb2c5ee2b501fa02c823bacdd303a",
            "require_email": false,
            "short_description": null,
            "slug": "bandana-punk-v4",
            "telegram_url": null,
            "twitter_username": null,
            "instagram_username": null,
            "wiki_url": null
        },
        "decimals": 0,
        "token_metadata": "https://ipfs.io/ipfs/bafkreihqarixzabuznlo36kjmcwedfiq2wkam64wvo5e6ohmeyphq6447u",
        "owner": {
            "user": {
                "username": null
            },
            "profile_img_url": require("./assets/owner/Screenshot.png"),
            "address": "0xff8f15c77db92f5388c0cf216e7fa6b51b49599b",
            "config": ""
        },
        "sell_orders": null,
        "creator": {
            "user": {
                "username": null
            },
            "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/32.png",
            "address": "0xff8f15c77db92f5388c0cf216e7fa6b51b49599b",
            "config": ""
        },
        "traits": [
            {
                "trait_type": "price",
                "value": "9",
                "display_type": null,
                "max_value": null,
                "trait_count": 1,
                "order": null
            }
        ],
        "last_sale": null,
        "top_bid": null,
        "listing_date": null,
        "is_presale": false,
        "transfer_fee_payment_token": null,
        "transfer_fee": null
    },
    {
        "id": 25903199,
        "token_id": "3",
        "num_sales": 0,
        "background_color": null,
        "image_url": "https://lh3.googleusercontent.com/Q1Y5C8jdc828wkjPuNf_DAz3cm90bh9CK6LZQLZzB3thOdegbRt3600vz5PhMnVggKddQD3rCH6JEGOd3VxidQ5H54SmBMg64eMpzw",
        "image_preview_url": "https://lh3.googleusercontent.com/Q1Y5C8jdc828wkjPuNf_DAz3cm90bh9CK6LZQLZzB3thOdegbRt3600vz5PhMnVggKddQD3rCH6JEGOd3VxidQ5H54SmBMg64eMpzw=s250",
        "image_thumbnail_url": "https://lh3.googleusercontent.com/Q1Y5C8jdc828wkjPuNf_DAz3cm90bh9CK6LZQLZzB3thOdegbRt3600vz5PhMnVggKddQD3rCH6JEGOd3VxidQ5H54SmBMg64eMpzw=s128",
        "image_original_url": require("./assets/nfts/6.jpg"),
        "animation_url": null,
        "animation_original_url": null,
        "name": "Captain America Punk",
        "description": null,
        "external_link": null,
        "asset_contract": {
            "address": "0xb6f41e1cb14df0f8e84e86090eaf6802354e8d02",
            "asset_contract_type": "non-fungible",
            "created_date": "2022-01-02T06:21:35.483307",
            "name": "Bandana Punk",
            "nft_version": "3.0",
            "opensea_version": null,
            "owner": 4950061,
            "schema_name": "ERC721",
            "symbol": "CPP",
            "total_supply": "0",
            "description": "",
            "external_link": null,
            "image_url": "https://lh3.googleusercontent.com/9B1oTFEv4DeaW9gFwnd1ION2NzfGnC9lHfjnPNSbNkDZmID0P7Di6Y6ptZxZuf0oaWgnAKLu1eqEbdlCJSpHDFUceo2D7H9c0wK56Q=s120",
            "default_to_fiat": false,
            "dev_buyer_fee_basis_points": 0,
            "dev_seller_fee_basis_points": 0,
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": 0,
            "opensea_seller_fee_basis_points": 250,
            "buyer_fee_basis_points": 0,
            "seller_fee_basis_points": 250,
            "payout_address": "0x2d9bb967505eb2c5ee2b501fa02c823bacdd303a"
        },
        "permalink": "https://testnets.opensea.io/assets/0xb6f41e1cb14df0f8e84e86090eaf6802354e8d02/3",
        "collection": {
            "banner_image_url": null,
            "chat_url": null,
            "created_date": "2022-01-02T06:32:35.565855",
            "default_to_fiat": false,
            "description": "",
            "dev_buyer_fee_basis_points": "0",
            "dev_seller_fee_basis_points": "0",
            "discord_url": null,
            "display_data": {
                "card_display_style": "contain",
                "images": []
            },
            "external_url": null,
            "featured": false,
            "featured_image_url": null,
            "hidden": false,
            "safelist_request_status": "not_requested",
            "image_url": "https://lh3.googleusercontent.com/9B1oTFEv4DeaW9gFwnd1ION2NzfGnC9lHfjnPNSbNkDZmID0P7Di6Y6ptZxZuf0oaWgnAKLu1eqEbdlCJSpHDFUceo2D7H9c0wK56Q=s120",
            "is_subject_to_whitelist": false,
            "large_image_url": "https://lh3.googleusercontent.com/9B1oTFEv4DeaW9gFwnd1ION2NzfGnC9lHfjnPNSbNkDZmID0P7Di6Y6ptZxZuf0oaWgnAKLu1eqEbdlCJSpHDFUceo2D7H9c0wK56Q",
            "medium_username": null,
            "name": "Bandana Punk V4",
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": "0",
            "opensea_seller_fee_basis_points": "250",
            "payout_address": "0x2d9bb967505eb2c5ee2b501fa02c823bacdd303a",
            "require_email": false,
            "short_description": null,
            "slug": "bandana-punk-v4",
            "telegram_url": null,
            "twitter_username": null,
            "instagram_username": null,
            "wiki_url": null
        },
        "decimals": 0,
        "token_metadata": "https://ipfs.io/ipfs/bafkreigamwjsidr37cn33arhpz52bcxfofmx4ssrtgev5ytduvapinqyvm",
        "owner": {
            "user": {
                "username": null
            },
            "profile_img_url": require("./assets/owner/Screenshot.png"),
            "address": "0xff8f15c77db92f5388c0cf216e7fa6b51b49599b",
            "config": ""
        },
        "sell_orders": null,
        "creator": {
            "user": {
                "username": null
            },
            "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/32.png",
            "address": "0xff8f15c77db92f5388c0cf216e7fa6b51b49599b",
            "config": ""
        },
        "traits": [
            {
                "trait_type": "price",
                "value": "17",
                "display_type": null,
                "max_value": null,
                "trait_count": 1,
                "order": null
            }
        ],
        "last_sale": null,
        "top_bid": null,
        "listing_date": null,
        "is_presale": false,
        "transfer_fee_payment_token": null,
        "transfer_fee": null
    },
    {
        "id": 25903251,
        "token_id": "4",
        "num_sales": 0,
        "background_color": null,
        "image_url": "https://lh3.googleusercontent.com/cFebPRhI6RMwGCHOtuGwvvNu4JFH_GRJpCG_0zFiHn03XAm-lCT__emfiZqdDCkkwRkg33ZP6avBv9iNDK8gtY4EKzvGz7jxA0DQxQ",
        "image_preview_url": "https://lh3.googleusercontent.com/cFebPRhI6RMwGCHOtuGwvvNu4JFH_GRJpCG_0zFiHn03XAm-lCT__emfiZqdDCkkwRkg33ZP6avBv9iNDK8gtY4EKzvGz7jxA0DQxQ=s250",
        "image_thumbnail_url": "https://lh3.googleusercontent.com/cFebPRhI6RMwGCHOtuGwvvNu4JFH_GRJpCG_0zFiHn03XAm-lCT__emfiZqdDCkkwRkg33ZP6avBv9iNDK8gtY4EKzvGz7jxA0DQxQ=s128",
        "image_original_url": require("./assets/nfts/1.jpg"),
        "animation_url": null,
        "animation_original_url": null,
        "name": "Blue Hat Punk",
        "description": null,
        "external_link": null,
        "asset_contract": {
            "address": "0xb6f41e1cb14df0f8e84e86090eaf6802354e8d02",
            "asset_contract_type": "non-fungible",
            "created_date": "2022-01-02T06:21:35.483307",
            "name": "Bandana Punk",
            "nft_version": "3.0",
            "opensea_version": null,
            "owner": 4950061,
            "schema_name": "ERC721",
            "symbol": "CPP",
            "total_supply": "0",
            "description": "",
            "external_link": null,
            "image_url": "https://lh3.googleusercontent.com/9B1oTFEv4DeaW9gFwnd1ION2NzfGnC9lHfjnPNSbNkDZmID0P7Di6Y6ptZxZuf0oaWgnAKLu1eqEbdlCJSpHDFUceo2D7H9c0wK56Q=s120",
            "default_to_fiat": false,
            "dev_buyer_fee_basis_points": 0,
            "dev_seller_fee_basis_points": 0,
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": 0,
            "opensea_seller_fee_basis_points": 250,
            "buyer_fee_basis_points": 0,
            "seller_fee_basis_points": 250,
            "payout_address": "0x2d9bb967505eb2c5ee2b501fa02c823bacdd303a"
        },
        "permalink": "https://testnets.opensea.io/assets/0xb6f41e1cb14df0f8e84e86090eaf6802354e8d02/4",
        "collection": {
            "banner_image_url": null,
            "chat_url": null,
            "created_date": "2022-01-02T06:32:35.565855",
            "default_to_fiat": false,
            "description": "",
            "dev_buyer_fee_basis_points": "0",
            "dev_seller_fee_basis_points": "0",
            "discord_url": null,
            "display_data": {
                "card_display_style": "contain",
                "images": []
            },
            "external_url": null,
            "featured": false,
            "featured_image_url": null,
            "hidden": false,
            "safelist_request_status": "not_requested",
            "image_url": "https://lh3.googleusercontent.com/9B1oTFEv4DeaW9gFwnd1ION2NzfGnC9lHfjnPNSbNkDZmID0P7Di6Y6ptZxZuf0oaWgnAKLu1eqEbdlCJSpHDFUceo2D7H9c0wK56Q=s120",
            "is_subject_to_whitelist": false,
            "large_image_url": "https://lh3.googleusercontent.com/9B1oTFEv4DeaW9gFwnd1ION2NzfGnC9lHfjnPNSbNkDZmID0P7Di6Y6ptZxZuf0oaWgnAKLu1eqEbdlCJSpHDFUceo2D7H9c0wK56Q",
            "medium_username": null,
            "name": "Bandana Punk V4",
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": "0",
            "opensea_seller_fee_basis_points": "250",
            "payout_address": "0x2d9bb967505eb2c5ee2b501fa02c823bacdd303a",
            "require_email": false,
            "short_description": null,
            "slug": "bandana-punk-v4",
            "telegram_url": null,
            "twitter_username": null,
            "instagram_username": null,
            "wiki_url": null
        },
        "decimals": 0,
        "token_metadata": "https://ipfs.io/ipfs/bafkreidrv52ozfz2odyyirbrbxspl3nphtfcwal7uq5t7imw6ldavswvbm",
        "owner": {
            "user": {
                "username": null
            },
            "profile_img_url": require("./assets/owner/Screenshot.png"),
            "address": "0xff8f15c77db92f5388c0cf216e7fa6b51b49599b",
            "config": ""
        },
        "sell_orders": null,
        "creator": {
            "user": {
                "username": null
            },
            "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/32.png",
            "address": "0xff8f15c77db92f5388c0cf216e7fa6b51b49599b",
            "config": ""
        },
        "traits": [
            {
                "trait_type": "price",
                "value": "2",
                "display_type": null,
                "max_value": null,
                "trait_count": 1,
                "order": null
            }
        ],
        "last_sale": null,
        "top_bid": null,
        "listing_date": null,
        "is_presale": false,
        "transfer_fee_payment_token": null,
        "transfer_fee": null
    },
    {
        "id": 25903464,
        "token_id": "5",
        "num_sales": 0,
        "background_color": null,
        "image_url": "https://lh3.googleusercontent.com/m-Ws730SPYfr1hhPi44UWd923AthhSYnetE8x32yJf1b4GPOTOwdsgK9yXN7naVm7Y884R7e7yTxzMjDGfwpZaRQmfgA4Zo5CXy_jg",
        "image_preview_url": "https://lh3.googleusercontent.com/m-Ws730SPYfr1hhPi44UWd923AthhSYnetE8x32yJf1b4GPOTOwdsgK9yXN7naVm7Y884R7e7yTxzMjDGfwpZaRQmfgA4Zo5CXy_jg=s250",
        "image_thumbnail_url": "https://lh3.googleusercontent.com/m-Ws730SPYfr1hhPi44UWd923AthhSYnetE8x32yJf1b4GPOTOwdsgK9yXN7naVm7Y884R7e7yTxzMjDGfwpZaRQmfgA4Zo5CXy_jg=s128",
        "image_original_url": require("./assets/nfts/2.jpg"),
        "animation_url": null,
        "animation_original_url": null,
        "name": "Green Hulk PunK",
        "description": null,
        "external_link": null,
        "asset_contract": {
            "address": "0xb6f41e1cb14df0f8e84e86090eaf6802354e8d02",
            "asset_contract_type": "non-fungible",
            "created_date": "2022-01-02T06:21:35.483307",
            "name": "Bandana Punk",
            "nft_version": "3.0",
            "opensea_version": null,
            "owner": 4950061,
            "schema_name": "ERC721",
            "symbol": "CPP",
            "total_supply": "0",
            "description": "",
            "external_link": null,
            "image_url": "https://lh3.googleusercontent.com/9B1oTFEv4DeaW9gFwnd1ION2NzfGnC9lHfjnPNSbNkDZmID0P7Di6Y6ptZxZuf0oaWgnAKLu1eqEbdlCJSpHDFUceo2D7H9c0wK56Q=s120",
            "default_to_fiat": false,
            "dev_buyer_fee_basis_points": 0,
            "dev_seller_fee_basis_points": 0,
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": 0,
            "opensea_seller_fee_basis_points": 250,
            "buyer_fee_basis_points": 0,
            "seller_fee_basis_points": 250,
            "payout_address": "0x2d9bb967505eb2c5ee2b501fa02c823bacdd303a"
        },
        "permalink": "https://testnets.opensea.io/assets/0xb6f41e1cb14df0f8e84e86090eaf6802354e8d02/5",
        "collection": {
            "banner_image_url": null,
            "chat_url": null,
            "created_date": "2022-01-02T06:32:35.565855",
            "default_to_fiat": false,
            "description": "",
            "dev_buyer_fee_basis_points": "0",
            "dev_seller_fee_basis_points": "0",
            "discord_url": null,
            "display_data": {
                "card_display_style": "contain",
                "images": []
            },
            "external_url": null,
            "featured": false,
            "featured_image_url": null,
            "hidden": false,
            "safelist_request_status": "not_requested",
            "image_url": "https://lh3.googleusercontent.com/9B1oTFEv4DeaW9gFwnd1ION2NzfGnC9lHfjnPNSbNkDZmID0P7Di6Y6ptZxZuf0oaWgnAKLu1eqEbdlCJSpHDFUceo2D7H9c0wK56Q=s120",
            "is_subject_to_whitelist": false,
            "large_image_url": "https://lh3.googleusercontent.com/9B1oTFEv4DeaW9gFwnd1ION2NzfGnC9lHfjnPNSbNkDZmID0P7Di6Y6ptZxZuf0oaWgnAKLu1eqEbdlCJSpHDFUceo2D7H9c0wK56Q",
            "medium_username": null,
            "name": "Bandana Punk V4",
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": "0",
            "opensea_seller_fee_basis_points": "250",
            "payout_address": "0x2d9bb967505eb2c5ee2b501fa02c823bacdd303a",
            "require_email": false,
            "short_description": null,
            "slug": "bandana-punk-v4",
            "telegram_url": null,
            "twitter_username": null,
            "instagram_username": null,
            "wiki_url": null
        },
        "decimals": 0,
        "token_metadata": "https://ipfs.io/ipfs/bafkreid74trb3iil3nvu3e2tgzwx7p75y5djowtjquc62l22qcl2y626su",
        "owner": {
            "user": {
                "username": null
            },
            "profile_img_url":   require("./assets/owner/Screenshot.png"),
            "address": "0xff8f15c77db92f5388c0cf216e7fa6b51b49599b",
            "config": ""
        },
        "sell_orders": null,
        "creator": {
            "user": {
                "username": null
            },
            "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/32.png",
            "address": "0xff8f15c77db92f5388c0cf216e7fa6b51b49599b",
            "config": ""
        },
        "traits": [
            {
                "trait_type": "price",
                "value": "14",
                "display_type": null,
                "max_value": null,
                "trait_count": 1,
                "order": null
            }
        ],
        "last_sale": null,
        "top_bid": null,
        "listing_date": null,
        "is_presale": false,
        "transfer_fee_payment_token": null,
        "transfer_fee": null
    }
]